# -*- coding: utf-8 -*-
# Generated by Protocol Buffers - manually implemented for seismic_data.proto

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
import json
import struct


@dataclass
class SEGYHeader:
    job_id: int = 0
    line_number: int = 0
    reel_number: int = 0
    num_traces: int = 0
    num_aux_traces: int = 0
    sample_interval: int = 0
    sample_interval_original: int = 0
    num_samples: int = 0
    num_samples_original: int = 0
    data_sample_format: int = 5
    ensemble_fold: int = 0
    trace_sorting: int = 0
    measurement_system: int = 1
    coordinate_units: int = 1
    num_priority: int = 0
    min_x: float = 0.0
    max_x: float = 0.0
    min_y: float = 0.0
    max_y: float = 0.0
    min_z: float = 0.0
    max_z: float = 0.0
    inline_min: int = 0
    inline_max: int = 0
    xline_min: int = 0
    xline_max: int = 0
    inline_step: int = 1
    xline_step: int = 1
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'job_id': self.job_id,
            'line_number': self.line_number,
            'reel_number': self.reel_number,
            'num_traces': self.num_traces,
            'num_aux_traces': self.num_aux_traces,
            'sample_interval': self.sample_interval,
            'sample_interval_original': self.sample_interval_original,
            'num_samples': self.num_samples,
            'num_samples_original': self.num_samples_original,
            'data_sample_format': self.data_sample_format,
            'ensemble_fold': self.ensemble_fold,
            'trace_sorting': self.trace_sorting,
            'measurement_system': self.measurement_system,
            'coordinate_units': self.coordinate_units,
            'num_priority': self.num_priority,
            'min_x': self.min_x,
            'max_x': self.max_x,
            'min_y': self.min_y,
            'max_y': self.max_y,
            'min_z': self.min_z,
            'max_z': self.max_z,
            'inline_min': self.inline_min,
            'inline_max': self.inline_max,
            'xline_min': self.xline_min,
            'xline_max': self.xline_max,
            'inline_step': self.inline_step,
            'xline_step': self.xline_step,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'SEGYHeader':
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})
    
    def serialize(self) -> bytes:
        return json.dumps(self.to_dict()).encode('utf-8')
    
    @classmethod
    def deserialize(cls, data: bytes) -> 'SEGYHeader':
        return cls.from_dict(json.loads(data.decode('utf-8')))


@dataclass
class BoundingBox:
    min_x: float = 0.0
    max_x: float = 0.0
    min_y: float = 0.0
    max_y: float = 0.0
    min_z: float = 0.0
    max_z: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'min_x': self.min_x, 'max_x': self.max_x,
            'min_y': self.min_y, 'max_y': self.max_y,
            'min_z': self.min_z, 'max_z': self.max_z,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BoundingBox':
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class DataBlock:
    block_id: str = ""
    level: int = 0
    inline_start: int = 0
    inline_end: int = 0
    xline_start: int = 0
    xline_end: int = 0
    depth_start: int = 0
    depth_end: int = 0
    num_inline: int = 0
    num_xline: int = 0
    num_depth: int = 0
    amplitude_data: bytes = b""
    min_amplitude: float = 0.0
    max_amplitude: float = 0.0
    bounding_box: Optional[BoundingBox] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'block_id': self.block_id,
            'level': self.level,
            'inline_start': self.inline_start,
            'inline_end': self.inline_end,
            'xline_start': self.xline_start,
            'xline_end': self.xline_end,
            'depth_start': self.depth_start,
            'depth_end': self.depth_end,
            'num_inline': self.num_inline,
            'num_xline': self.num_xline,
            'num_depth': self.num_depth,
            'amplitude_data': list(self.amplitude_data),
            'min_amplitude': self.min_amplitude,
            'max_amplitude': self.max_amplitude,
            'bounding_box': self.bounding_box.to_dict() if self.bounding_box else None,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DataBlock':
        bb_data = data.get('bounding_box')
        return cls(
            block_id=data.get('block_id', ''),
            level=data.get('level', 0),
            inline_start=data.get('inline_start', 0),
            inline_end=data.get('inline_end', 0),
            xline_start=data.get('xline_start', 0),
            xline_end=data.get('xline_end', 0),
            depth_start=data.get('depth_start', 0),
            depth_end=data.get('depth_end', 0),
            num_inline=data.get('num_inline', 0),
            num_xline=data.get('num_xline', 0),
            num_depth=data.get('num_depth', 0),
            amplitude_data=bytes(data.get('amplitude_data', [])),
            min_amplitude=data.get('min_amplitude', 0.0),
            max_amplitude=data.get('max_amplitude', 0.0),
            bounding_box=BoundingBox.from_dict(bb_data) if bb_data else None,
        )
    
    def serialize(self) -> bytes:
        return json.dumps(self.to_dict()).encode('utf-8')
    
    @classmethod
    def deserialize(cls, data: bytes) -> 'DataBlock':
        return cls.from_dict(json.loads(data.decode('utf-8')))


@dataclass
class BlockInfo:
    block_id: str = ""
    level: int = 0
    bounding_box: Optional[BoundingBox] = None
    data_size: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'block_id': self.block_id,
            'level': self.level,
            'bounding_box': self.bounding_box.to_dict() if self.bounding_box else None,
            'data_size': self.data_size,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BlockInfo':
        bb_data = data.get('bounding_box')
        return cls(
            block_id=data.get('block_id', ''),
            level=data.get('level', 0),
            bounding_box=BoundingBox.from_dict(bb_data) if bb_data else None,
            data_size=data.get('data_size', 0),
        )


@dataclass
class DatasetMetadata:
    dataset_id: str = ""
    name: str = ""
    file_size: int = 0
    header: Optional[SEGYHeader] = None
    blocks: List[BlockInfo] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'dataset_id': self.dataset_id,
            'name': self.name,
            'file_size': self.file_size,
            'header': self.header.to_dict() if self.header else None,
            'blocks': [b.to_dict() for b in self.blocks],
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DatasetMetadata':
        hdr_data = data.get('header')
        blocks_data = data.get('blocks', [])
        return cls(
            dataset_id=data.get('dataset_id', ''),
            name=data.get('name', ''),
            file_size=data.get('file_size', 0),
            header=SEGYHeader.from_dict(hdr_data) if hdr_data else None,
            blocks=[BlockInfo.from_dict(b) for b in blocks_data],
        )


@dataclass
class ProgressUpdate:
    percent_complete: float = 0.0
    message: str = ""
    bytes_processed: int = 0
    total_bytes: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'percent_complete': self.percent_complete,
            'message': self.message,
            'bytes_processed': self.bytes_processed,
            'total_bytes': self.total_bytes,
        }


@dataclass
class ErrorMessage:
    code: int = 0
    message: str = ""
    details: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'code': self.code,
            'message': self.message,
            'details': self.details,
        }


@dataclass
class BlockRequest:
    block_ids: List[str] = field(default_factory=list)
    level: int = 0
    stream: bool = True
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'block_ids': self.block_ids,
            'level': self.level,
            'stream': self.stream,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BlockRequest':
        return cls(
            block_ids=data.get('block_ids', []),
            level=data.get('level', 0),
            stream=data.get('stream', True),
        )


@dataclass
class ViewFrustum:
    matrix: List[float] = field(default_factory=list)
    fov: float = 60.0
    aspect: float = 1.0
    near: float = 0.1
    far: float = 1000.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'matrix': self.matrix,
            'fov': self.fov,
            'aspect': self.aspect,
            'near': self.near,
            'far': self.far,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ViewFrustum':
        return cls(
            matrix=data.get('matrix', []),
            fov=data.get('fov', 60.0),
            aspect=data.get('aspect', 1.0),
            near=data.get('near', 0.1),
            far=data.get('far', 1000.0),
        )


class MessageType:
    HEADER = 0
    DATA_BLOCK = 1
    METADATA = 2
    PROGRESS = 3
    ERROR = 4
    COMPLETE = 5
    REQUEST_BLOCK = 6
    VIEW_FRUSTUM = 7


@dataclass
class WebSocketMessage:
    type: int = 0
    request_id: str = ""
    header: Optional[SEGYHeader] = None
    data_block: Optional[DataBlock] = None
    metadata: Optional[DatasetMetadata] = None
    progress: Optional[ProgressUpdate] = None
    error: Optional[ErrorMessage] = None
    block_request: Optional[BlockRequest] = None
    view_frustum: Optional[ViewFrustum] = None
    
    def to_dict(self) -> Dict[str, Any]:
        result = {
            'type': self.type,
            'request_id': self.request_id,
        }
        if self.header is not None:
            result['header'] = self.header.to_dict()
        if self.data_block is not None:
            result['data_block'] = self.data_block.to_dict()
        if self.metadata is not None:
            result['metadata'] = self.metadata.to_dict()
        if self.progress is not None:
            result['progress'] = self.progress.to_dict()
        if self.error is not None:
            result['error'] = self.error.to_dict()
        if self.block_request is not None:
            result['block_request'] = self.block_request.to_dict()
        if self.view_frustum is not None:
            result['view_frustum'] = self.view_frustum.to_dict()
        return result
    
    def serialize(self) -> bytes:
        return json.dumps(self.to_dict()).encode('utf-8')
    
    @classmethod
    def deserialize(cls, data: bytes) -> 'WebSocketMessage':
        parsed = json.loads(data.decode('utf-8'))
        msg = cls(
            type=parsed.get('type', 0),
            request_id=parsed.get('request_id', ''),
        )
        if 'header' in parsed:
            msg.header = SEGYHeader.from_dict(parsed['header'])
        if 'data_block' in parsed:
            msg.data_block = DataBlock.from_dict(parsed['data_block'])
        if 'metadata' in parsed:
            msg.metadata = DatasetMetadata.from_dict(parsed['metadata'])
        if 'progress' in parsed:
            p = parsed['progress']
            msg.progress = ProgressUpdate(
                percent_complete=p.get('percent_complete', 0),
                message=p.get('message', ''),
                bytes_processed=p.get('bytes_processed', 0),
                total_bytes=p.get('total_bytes', 0),
            )
        if 'error' in parsed:
            e = parsed['error']
            msg.error = ErrorMessage(
                code=e.get('code', 0),
                message=e.get('message', ''),
                details=e.get('details', ''),
            )
        if 'block_request' in parsed:
            msg.block_request = BlockRequest.from_dict(parsed['block_request'])
        if 'view_frustum' in parsed:
            msg.view_frustum = ViewFrustum.from_dict(parsed['view_frustum'])
        return msg
